FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml .
RUN pip install uv
RUN uv pip install --system --no-cache-dir .
COPY src ./src
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
